# Generated by Django 3.2.8 on 2023-09-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=8)),
            ],
        ),
    ]
