# Generated by Django 3.2.8 on 2023-10-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='year',
        ),
    ]
